import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`flex font-doHyeon m-auto w-[70%] min-w-[500px] border-2 h-screen`}>{children}</body>
        </html>
    );
}
